# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
    tags:

jobs:
  debug_ctx:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  Linux:
    runs-on: ubuntu-18.04
    env:
      DOCKER_BUILDKIT: 1

    strategy:
      matrix:
        boards: [arm-01]
    steps:
    - name: Determine Target Branches
      id: gittargets
      shell: bash
      run: |
        TESTING_REF="master"  # Always use master for testing
        OS_REF=""
        APPS_REF=""
        
        REF=$GITHUB_REF
        
        # If a base ref is set this is a PR and we will want to use
        # the base ref instead of the ref that triggered the event
        if [ ${GITHUB_BASE_REF} ]; then
          REF=refs/heads/$GITHUB_BASE_REF
        fi
          
        echo "Working with ref: $REF"
        
        # We modify for all tags and release branches
        if [[ $REF =~ refs/heads/releases/*|refs/tags/* ]]; then
          if [[ $REF =~ refs/heads/* ]]
            then
              REF_NAME=${REF##refs/heads/}
              echo "Working with a branch: $REF_NAME"
            else
              REF_NAME=${REF##refs/tags/}
              echo "Working with a tag: $REF_NAME"
          fi
        
          # Determine the repo and leave that unset to use the normal checkout behavior
          # of using the merge commit instead of HEAD
          case $GITHUB_REPOSITORY in
            "btashton/incubator-nuttx")
              # OS
              echo "Triggered by change in OS"
              APPS_REF=$REF_NAME
              ;;
        
            "btashton/incubator-nuttx-apps" )
              # APPS
              OS_REF=$REF_NAME
              echo "Triggered by change in APPS"
              ;;
        
            *)
              echo "Trigger by change on $GITHUB_REPOSITORY. This is unexpected."
              ;;
          esac
        fi
        
        echo ::set-output name=os_ref::$OS_REF
        echo ::set-output name=apps_ref::$APPS_REF
        echo ::set-output name=testing_ref::$TESTING_REF

    - name: Checkout nuttx repo
      uses: actions/checkout@v2
      with:
        repository: btashton/incubator-nuttx
        ref: ${{ steps.gittargets.outputs.os_ref }}
        path: nuttx
        fetch-depth: 0

    - name: Fetch nuttx tags
      run: |
        cd nuttx
        git fetch --tags

    - name: Checkout apps repo
      uses: actions/checkout@v2
      with:
        repository: btashton/incubator-nuttx-apps
        ref: ${{ steps.gittargets.outputs.apps_ref }}
        path: apps
        fetch-depth: 0

    - name: Checkout testing repo
      uses: actions/checkout@v2
      with:
        repository: btashton/incubator-nuttx-testing
        ref: ${{ steps.gittargets.outputs.testing_ref }}
        path: testing
